

var HeroList_Strength = [
    { name : 'Abaddon', name_sc : '亚巴顿', name_game : 'npc_dota_hero_abaddon' },
    { name : 'Alchemist', name_sc : '炼金术士', name_game : 'npc_dota_hero_alchemist'},
    { name : 'Axe', name_sc : '斧王', name_game : 'npc_dota_hero_axe'},
    { name : 'Underlord', name_sc : '孽主', name_game : 'npc_dota_hero_abyssal_underlord'},
    { name : 'Beastmaster', name_sc : '兽王', name_game : 'npc_dota_hero_beastmaster'},
    { name : 'Brewmaster', name_sc : '酒仙', name_game : 'npc_dota_hero_brewmaster'},
    { name : 'Bristleback', name_sc : '刚被兽', name_game : 'npc_dota_hero_bristleback'},
    { name : 'Centaur Warrunner', name_sc : '人马', name_game : 'npc_dota_hero_centaur'},
    { name : 'Chaos Knight', name_sc : '混沌骑士', name_game : 'npc_dota_hero_chaos_knight'},
    { name : 'Doom', name_sc : '末日使者', name_game : 'npc_dota_hero_doom_bringer'},
    { name : 'Dragon Knight', name_sc : '龙骑士', name_game : 'npc_dota_hero_dragon_knight'},
    { name : 'Earth Spirit', name_sc : '大地之灵', name_game : 'npc_dota_hero_earth_spirit'},
    { name : 'Earthshaker', name_sc : '撼地神牛', name_game : 'npc_dota_hero_earthshaker'},
    { name : 'Elder Titan', name_sc : '上古巨神', name_game : 'npc_dota_hero_elder_titan'},
    { name : 'Huskar', name_sc : '哈斯卡', name_game : 'npc_dota_hero_huskar'},
    { name : 'kunkka', name_sc : '昆卡', name_game : 'npc_dota_hero_kunkka'},
    { name : 'Legion Commander', name_sc : '军团指挥官', name_game : 'npc_dota_hero_legion_commander'},
    { name : 'Lifestealer', name_sc : '噬魂鬼', name_game : 'npc_dota_hero_life_stealer'},
    { name : 'Lycan', name_sc : '狼人', name_game : 'npc_dota_hero_lycan'},
    { name : 'Magnus', name_sc : '马格纳斯', name_game : 'npc_dota_hero_magnataur'},
    { name : 'Night Stalker', name_sc : '暗夜魔王', name_game : 'npc_dota_hero_night_stalker'},
    { name : 'Omniknight', name_sc : '全能骑士', name_game : 'npc_dota_hero_omniknight'},
    { name : 'Phoenix', name_sc : '凤凰', name_game : 'npc_dota_hero_phoenix'},
    { name : 'Pudge', name_sc : '屠夫', name_game : 'npc_dota_hero_pudge'},
    { name : 'Clockwerk', name_sc : '发条技师', name_game : 'npc_dota_hero_rattletrap'},
    { name : 'Sand King', name_sc : '沙王', name_game : 'npc_dota_hero_sand_king'},
    { name : 'Timbersaw', name_sc : '伐木机', name_game : 'npc_dota_hero_shredder'},
    { name : 'Wraith King', name_sc : '骷髅王', name_game : 'npc_dota_hero_skeleton_king'},
    { name : 'Slardar', name_sc : '大鱼人', name_game : 'npc_dota_hero_slardar'},
    { name : 'Spirit Breaker', name_sc : '裂魂人', name_game : 'npc_dota_hero_spirit_breaker'},
    { name : 'Sven', name_sc : '斯温', name_game : 'npc_dota_hero_sven'},
    { name : 'Tidehunter', name_sc : '潮汐猎人', name_game : 'npc_dota_hero_tidehunter'},
    { name : 'Tiny', name_sc : '小小', name_game : 'npc_dota_hero_tiny'},
    { name : 'Treant Protector', name_sc : '树精卫士', name_game : 'npc_dota_hero_treant'},
    { name : 'Tusk', name_sc : '海民', name_game : 'npc_dota_hero_tusk'},
    { name : 'Undying', name_sc : '尸王', name_game : 'npc_dota_hero_undying'},
    { name : 'Io', name_sc : '小精灵', name_game : 'npc_dota_hero_wisp'},
    { name : 'Mars', name_sc : '玛尔斯', name_game : 'npc_dota_hero_mars'},
]


var HeroList_Agility = [
    { name : 'Anti-Mage', name_sc : '敌法师', name_game : 'npc_dota_hero_antimage'},
    { name : 'Arc Warden', name_sc : '天穹守望者', name_game : 'npc_dota_hero_arc_warden'},
    { name : 'Bloodseeker', name_sc : '血魔', name_game : 'npc_dota_hero_bloodseeker'},
    { name : 'Bounty Hunter', name_sc : '赏金猎人', name_game : 'npc_dota_hero_bounty_hunter'},
    { name : 'Broodmother', name_sc : '育母蜘蛛', name_game : 'npc_dota_hero_broodmother'},
    { name : 'Clinkz', name_sc : '克林克兹', name_game : 'npc_dota_hero_clinkz'},
    { name : 'Drow Ranger', name_sc : '卓尔游侠', name_game : 'npc_dota_hero_drow_ranger'},
    { name : 'Ember Spirit', name_sc : '火猫', name_game : 'npc_dota_hero_ember_spirit'},
    { name : 'Faceless Void', name_sc : '虚空假面', name_game : 'npc_dota_hero_faceless_void'},
    { name : 'Gyrocopter', name_sc : '矮人直升机', name_game : 'npc_dota_hero_gyrocopter'},
    { name : 'Juggernaut', name_sc : '剑圣', name_game : 'npc_dota_hero_juggernaut'},
    { name : 'Lone Druid', name_sc : '德鲁伊', name_game : 'npc_dota_hero_lone_druid'},
    { name : 'Luna', name_sc : '露娜', name_game : 'npc_dota_hero_luna'},
    { name : 'Medusa', name_sc : '美杜莎', name_game : 'npc_dota_hero_medusa'},
    { name : 'Meepo', name_sc : '米波', name_game : 'npc_dota_hero_meepo'},
    { name : 'Mirana', name_sc : '米拉娜', name_game : 'npc_dota_hero_mirana'},
    { name : 'Morphling', name_sc : '变体精灵', name_game : 'npc_dota_hero_morphling'},
    { name : 'Monkey King', name_sc : '齐天大圣', name_game : 'npc_dota_hero_monkey_king'},
    { name : 'Naga Siren', name_sc : '娜迦海妖', name_game : 'npc_dota_hero_naga_siren'},
    { name : 'Shadow Fiend', name_sc : '影魔', name_game : 'npc_dota_hero_nevermore'},
    { name : 'Nyx Assassin', name_sc : '司夜刺客', name_game : 'npc_dota_hero_nyx_assassin'},
    { name : 'Pangolier', name_sc : '石鳞剑士', name_game : 'npc_dota_hero_pangolier'},
    { name : 'Phantom Assassin', name_sc : '幻影刺客', name_game : 'npc_dota_hero_phantom_assassin'},
    { name : 'Phantom Lancer', name_sc : '幻影长矛手', name_game : 'npc_dota_hero_phantom_lancer'},
    { name : 'Razor', name_sc : '剃刀', name_game : 'npc_dota_hero_razor'},
    { name : 'Riki', name_sc : '力丸', name_game : 'npc_dota_hero_riki'},
    { name : 'Slark', name_sc : '小鱼人', name_game : 'npc_dota_hero_slark'},
    { name : 'Sniper', name_sc : '狙击手', name_game : 'npc_dota_hero_sniper'},
    { name : 'Spectre', name_sc : '幽鬼', name_game : 'npc_dota_hero_spectre'},
    { name : 'Templar Assassin', name_sc : '圣堂刺客', name_game : 'npc_dota_hero_templar_assassin'},
    { name : 'Terrorblade', name_sc : '恐怖利刃', name_game : 'npc_dota_hero_terrorblade'},
    { name : 'Troll Warlord', name_sc : '巨魔战将', name_game : 'npc_dota_hero_troll_warlord'},
    { name : 'Ursa', name_sc : '熊战士', name_game : 'npc_dota_hero_ursa'},
    { name : 'Vengeful Spirit', name_sc : '复仇之魂', name_game : 'npc_dota_hero_vengefulspirit'},
    { name : 'Venomancer', name_sc : '剧毒术士', name_game : 'npc_dota_hero_venomancer'},
    { name : 'Viper', name_sc : '冥界亚龙', name_game : 'npc_dota_hero_viper'},
    { name : 'Weaver', name_sc : '编织者', name_game : 'npc_dota_hero_weaver'},
]


var HeroList_Intelligence = [
    { name : 'Ancient Apparition', name_sc : '冰魂', name_game : 'npc_dota_hero_ancient_apparition'},
    { name : 'Bane', name_sc : '痛苦之源', name_game : 'npc_dota_hero_bane'},
    { name : 'Batrider', name_sc : '蝙蝠骑士', name_game : 'npc_dota_hero_batrider'},
    { name : 'Chen', name_sc : '陈', name_game : 'npc_dota_hero_chen'},
    { name : 'Crystal Maiden', name_sc : '冰女', name_game : 'npc_dota_hero_crystal_maiden'},
    { name : 'Dark Seer', name_sc : '黑贤', name_game : 'npc_dota_hero_dark_seer'},
    { name : 'Dark Willow', name_sc : '邪影芳灵', name_game : 'npc_dota_hero_dark_willow'},
    { name : 'Dazzle', name_sc : '戴泽', name_game : 'npc_dota_hero_dazzle'},
    { name : 'Death Prophet', name_sc : '死亡先知', name_game : 'npc_dota_hero_death_prophet'},
    { name : 'Disruptor', name_sc : '干扰者', name_game : 'npc_dota_hero_disruptor'},
    { name : 'Enchantress', name_sc : '魅惑魔女', name_game : 'npc_dota_hero_enchantress'},
    { name : 'Enigma', name_sc : '谜团', name_game : 'npc_dota_hero_enigma'},
    { name : 'Furion', name_sc : '先知', name_game : 'npc_dota_hero_furion'},
    { name : 'Grimstroke', name_sc : '天涯墨客', name_game : 'npc_dota_hero_grimstroke'},
    { name : 'Invoker', name_sc : '卡尔', name_game : 'npc_dota_hero_invoker'},
    { name : 'Jakiro', name_sc : '双头龙', name_game : 'npc_dota_hero_jakiro'},
    { name : 'Keeper of the Light', name_sc : '光之守卫', name_game : 'npc_dota_hero_keeper_of_the_light'},
    { name : 'Leshrac', name_sc : '拉席克', name_game : 'npc_dota_hero_leshrac'},
    { name : 'Lich', name_sc : '巫妖', name_game : 'npc_dota_hero_lich'},
    { name : 'Lina', name_sc : '莉娜', name_game : 'npc_dota_hero_lina'},
    { name : 'Lion', name_sc : '莱恩', name_game : 'npc_dota_hero_lion'},
    { name : 'Necrophos', name_sc : '瘟疫法师', name_game : 'npc_dota_hero_necrolyte'},
    { name : 'Outworld Devourer', name_sc : '殁境神蚀者', name_game : 'npc_dota_hero_obsidian_destroyer'},
    { name : 'Ogre Magi', name_sc : '食人魔魔法师', name_game : 'npc_dota_hero_ogre_magi'},
    { name : 'Oracle', name_sc : '神谕者', name_game : 'npc_dota_hero_oracle'},
    { name : 'Puck', name_sc : '帕克', name_game : 'npc_dota_hero_puck'},
    { name : 'Pugna', name_sc : '帕格纳', name_game : 'npc_dota_hero_pugna'},
    { name : 'Queen of Pain', name_sc : '痛苦女王', name_game : 'npc_dota_hero_queenofpain'},
    { name : 'Rubick', name_sc : '拉比克', name_game : 'npc_dota_hero_rubick'},
    { name : 'Shadow Demon', name_sc : '暗影恶魔', name_game : 'npc_dota_hero_shadow_demon'},
    { name : 'Shadow Shaman', name_sc : '暗影萨满', name_game : 'npc_dota_hero_shadow_shaman'},
    { name : 'Silencer', name_sc : '沉默术士', name_game : 'npc_dota_hero_silencer'},
    { name : 'Skywrath Mage', name_sc : '天怒法师', name_game : 'npc_dota_hero_skywrath_mage'},
    { name : 'Storm Spirit', name_sc : '风暴之灵', name_game : 'npc_dota_hero_storm_spirit'},
    { name : 'Techies', name_sc : '地精工程师', name_game : 'npc_dota_hero_techies'},
    { name : 'Tinker', name_sc : '修补匠', name_game : 'npc_dota_hero_tinker'},
    { name : 'Visage', name_sc : '维萨吉', name_game : 'npc_dota_hero_visage'},
    { name : 'Warlock', name_sc : '术士', name_game : 'npc_dota_hero_warlock'},
    { name : 'Windranger', name_sc : '风行者', name_game : 'npc_dota_hero_windrunner'},
    { name : 'Winter Wyvern', name_sc : '寒冬飞龙', name_game : 'npc_dota_hero_winter_wyvern'},
    { name : 'Witch Doctor', name_sc : '巫医', name_game : 'npc_dota_hero_witch_doctor'},
    { name : 'Zeus', name_sc : '宙斯', name_game : 'npc_dota_hero_zuus'},
]